services:
  backend:
    profiles: [prod]
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      TOKEN_LIFETIME_REFRESH_THRESHOLD: ${TOKEN_LIFETIME_REFRESH_THRESHOLD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  
  frontend:
    profiles: [prod]
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

  database:
    profiles: [prod]
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/indices.sql:/docker-entrypoint-initdb.d/02-indices.sql:ro
      - ./database/triggers.sql:/docker-entrypoint-initdb.d/03-triggers.sql:ro
      - ./database/data.sql:/docker-entrypoint-initdb.d/04-data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  
  database-dev:
    extends: database
    profiles: [dev]
    ports:
      - "5432:5432"
  
  redis:
    profiles: [prod]
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - app-network
  
  redis-dev:
    extends: redis
    profiles: [dev]
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata:

networks:
  app-network:
    driver: bridge